def make_prompt(prev, curr, next_, title, abstract):
    return (
        "Below are three consecutive sentences from a research paper, along with the paper's title and abstract.\n"
        "Given these, generate a natural language query in the style of a researcher asking, for example, 'Are there any research papers on ...', 'Are there any studies that ...', or 'Are there any tools or resources for ...'.\n"
        "The query should reflect the main research topic, method, or concept implied by the context, focusing on what the cited paper is likely about.\n"
        "Do not copy or closely paraphrase the current sentence; instead, use the overall context to infer the research topic or method.\n"
        "The query should be specific enough to retrieve relevant papers, but not limited to the exact wording of the current sentence.\n"
        "Output only the search query itself, without any unnecessary prefixes or explanations.\n\n"
        "Example 1:\n"
        "Previous sentence: Deep generative models have shown remarkable success in image synthesis tasks.\n"
        "Current sentence: Recent advances leverage adversarial training to improve sample quality.\n"
        "Next sentence: However, training instability remains a significant challenge.\n"
        "Title: Generative Adversarial Networks for Image Synthesis\n"
        "Abstract: This paper explores the use of generative adversarial networks for high-quality image synthesis, discussing recent advances and challenges in training stability.\n"
        "Query: Are there any research papers on generative models for image synthesis and adversarial training methods?\n\n"
        "Example 2:\n"
        "Previous sentence: Temporal consistency is crucial for video generation.\n"
        "Current sentence: Several approaches use optical flow to enforce smooth transitions between frames.\n"
        "Next sentence: Despite these efforts, artifacts still occur in challenging scenarios.\n"
        "Title: Improving Temporal Consistency in Video Generation\n"
        "Abstract: We propose new methods for enforcing temporal consistency in video generation, focusing on the use of optical flow and addressing common artifacts.\n"
        "Query: Are there any studies that explore methods for improving temporal consistency in video generation using optical flow?\n\n"
        "Example 3:\n"
        "Previous sentence: Self-supervised learning has gained popularity in representation learning.\n"
        "Current sentence: Contrastive loss functions are commonly used to train such models.\n"
        "Next sentence: These methods have been applied to various domains including vision and language.\n"
        "Title: Self-Supervised Representation Learning with Contrastive Loss\n"
        "Abstract: This work surveys self-supervised learning techniques using contrastive loss, with applications in vision and language domains.\n"
        "Query: Are there any research papers on self-supervised representation learning with contrastive loss in vision and language?\n\n"
        "Now, generate a query for the following context:\n"
        f"Previous sentence: {prev}\n"
        f"Current sentence: {curr}\n"
        f"Next sentence: {next_}\n"
        f"Title: {title}\n"
        f"Abstract: {abstract}\n"
        "Query:"
    )
