train:
  lr: 2e-4
  batch_size: 8
  epochs: 5
  margin: 1.0
  eval_steps: 50
  weight_decay: 0.01
  warmup_ratio: 0.1
  output_dir: ./specter2_adhoc_query_finetuned
  datasets_dir: ./datasets
  train_key: train_data
  val_key: val_data
  test_key: test_data
