train:
  lr: 2e-4
  batch_size: 8
  epochs: 5
  margin: 1.0
  eval_steps: 50
  weight_decay: 0.01
  warmup_ratio: 0.1
  output_dir: /workspace/model
  datasets_dir: ./datasets
  train_key: train
  val_key: val
  test_key: test
