train:
  lr: 1e-4
  batch_size: 256
  epochs: 6
  margin: 1.0
  eval_steps: 50
  weight_decay: 0.01
  warmup_ratio: 0.1
  output_dir: ./finetune_model
  datasets_dir: ../../data/datasets
  train_key: train
  val_key: val
  test_key: test
